add debinstall. update all the things. mostly just code cleanup

diff --git a/google b/google
--- a/google
+++ b/google
@@ -2,8 +2,20 @@
 # Google command line search shortcut
 # By Ad@m <http://hbang.ws>
 # Licensed under the MIT License <http://adam.mit-license.org>
-OPENER=echo
-[[ -f "/usr/bin/open" ]]&&OPENER=/usr/bin/open
-[[ -f "/usr/bin/openurl" ]]&&OPENER=/usr/bin/openurl
-[[ -f "/usr/bin/sbopenurl" ]]&&OPENER=/usr/bin/sbopenurl
-$OPENER "http://www.google.com/search?q=$*"
+
+opener="oops"
+
+if [[ -f "/usr/bin/sbopenurl" ]]; then
+	opener=/usr/bin/sbopenurl
+elif [[ -f "/usr/bin/openurl" ]]; then
+	opener=/usr/bin/openurl
+elif [[ -f "/usr/bin/open" ]]; then
+	opener=/usr/bin/open
+elif [[ -f "/usr/bin/lynx" ]]; then
+	opener=/usr/bin/lynx
+else
+	echo "Oops, I couldn't find a command that allows me to open a browser." >&2
+	exit 1
+fi
+
+$opener "http://www.google.com/search?q=$*"
diff --git a/spring b/spring
--- a/spring
+++ b/spring
@@ -4,16 +4,22 @@
 # Licensed under the MIT License <http://adam.mit-license.org>
 # Usage: spring [-s|-l]
 #   s = safe mode; l = non-locking ("changing language") respring
+
 if [[ "$1" == "-s" ]]; then
 	killall -ABRT SpringBoard
 elif [[ "$1" == "-l" ]]; then
 	if [[ ! -f "/usr/bin/cycript" ]]; then
-		echo "spring: cycript required for language respring">&2
+		echo "spring: cycript required for language respring" >&2
 		exit 1
 	fi
-	echo "[UIApp languageChanged]">/tmp/spring.cy
-	cycript -p SpringBoard /tmp/spring.cy
-	rm /tmp/spring.cy
+
+	echo "[UIApp languageChanged]" > /tmp/spring_langchange.cy
+	cycript -p SpringBoard /tmp/spring_langchange.cy
 else
-	killall SpringBoard
+	if [[ -f "/usr/bin/cycript" ]]; then
+		echo "[UIApp _relaunchSpringBoardNow]" > /tmp/spring.cy
+		cycript -p SpringBoard /tmp/spring.cy
+	else
+		killall backboardd || killall SpringBoard
+	fi
 elif
