add non-locking respring

diff --git a/spring b/spring
--- a/spring
+++ b/spring
@@ -2,4 +2,18 @@
 # Respring/safe mode shortcut
 # By Ad@m <http://hbang.ws>
 # Licensed under the MIT License <http://adam.mit-license.org>
-[[ "$1" == "-s" ]]&&killall -ABRT SpringBoard||killall SpringBoard
+# Usage: spring [-s|-l]
+#   s = safe mode; l = non-locking ("changing language") respring
+if [[ "$1" == "-s" ]]; then
+	killall -ABRT SpringBoard;
+elif [[ "$1" == "-l" ]]; then
+	if [[ ! -f "/usr/bin/cycript" ]]; then
+		echo "spring: cycript required for language respring">&2
+		exit 1
+	fi
+	echo "[UIApp languageChanged]">/tmp/spring.cy
+	cycript -p SpringBoard /tmp/spring.cy
+	rm /tmp/spring.cy
+else
+	killall SpringBoard
+elif
